theme = "fleet_dark"

[editor]
true-color = true
line-number = "relative"
idle-timeout = 100

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true

[keys.normal]
C-s = ":w"
C-q = ":q"

esc = ["collapse_selection", "keep_primary_selection"]
