[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-servers = ["pyright-langserver"]
auto-format = true
formatter = { command = "black", args = ["-", "--quiet"] }

[language-server.pyright-langserver]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "kotlin"
roots = ["build.gradle.kts"]
language-servers = ["kls"]

[language-server.kls]
command = "kls"

[[language]]
name = "java"
formatter = { command = "gjf" }
auto-format = true
language-servers = ["jdtls"]

[language-server.jdtls]
command = "jdtls"

[[language]]
name = "prolog"
scope = "source.prolog"
roots = []
file-types = ["pl", "prolog"]
comment-token = "%"
language-servers = ["swipl"]

[language-server.swipl]
command = "swipl"
args = [
  "-g",
  "use_module(library(lsp_server))",
  "-g",
  "lsp_server:main",
  "-t",
  "halt",
  "--",
  "stdio",
]

[language-server.biome]
command = "biome"
args = ["lsp-proxy", "--config-path=biome.json"]

[[language]]
name = "javascript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "jsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]
