[[language]]
name = "python"
roots = ["pyproject.toml"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {} # <- this is the important line

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "kotlin"
roots = ["build.gradle.kts"]
language-server = { command = "kls" }
