source "%val{config}/plugins/plug.kak/rc/plug.kak"

# defaults
map global normal <c-q> ': quit<ret>'
map global normal <c-s> ': write<ret>'
set-option global tabstop 4
add-highlighter global/ number-lines

# copy paste to system
hook global NormalKey y|d|c %{ nop %sh{
      printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
}}
map global user P '!xsel --output --clipboard<ret>'
map global user p '<a-!>xsel --output --clipboard<ret>'

# fzf
plug "andreyorst/fzf.kak"
map global normal <c-p> ': fzf-mode<ret>'

# plugins
plug "occivink/kakoune-sudo-write"

